#!/usr/bin/env python3
"""Snapshot the CLI's public surface, so a refactor can prove it moved nothing.

WHY THIS EXISTS. Issue #193 asks for `src/provael/cli.py` — 3,000-odd lines and 27 top-level
commands — to be split, and states the acceptance plainly: `provael --help` and every
`provael <cmd> --help` must render identically before and after, because the surface is what
adopters have pinned in their own scripts. That acceptance is unverifiable by reading a
2,000-line file move. This makes it mechanical.

WHAT IS CAPTURED, AND WHY NOT THE RENDERED TEXT. `--help` output wraps to the terminal, so a
byte-comparison of it fails on a different `COLUMNS` and passes on a genuinely lost option that
happened to reflow. So the snapshot is the surface as DATA: the command list in registration
order (which is the order `--help` prints), and for each command its help text, its parameter
names, their flags, and whether each is required. A lost option, a renamed flag, a reordered
command list and a dropped help string all change this file; a terminal width does not.

ORDER IS PART OF THE SURFACE. Typer prints commands in registration order, so a split that
registers them in a different order changes what a reader sees even though every command still
exists. That is exactly the kind of "it still works" regression a file move produces, so the
lists here are deliberately NOT sorted.

Usage::

    python scripts/gen_cli_surface.py            # rewrite
    python scripts/gen_cli_surface.py --check    # fail if the surface moved
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from typer.main import get_command  # noqa: E402

from provael.cli import app  # noqa: E402

OUT = ROOT / "tests" / "fixtures" / "cli-surface.json"

NOTE = (
    "GENERATED by scripts/gen_cli_surface.py. The CLI's public surface as data: command order, "
    "help text, parameter names and flags. Regenerate ONLY when the surface is meant to change, "
    "and say so in the commit — a diff here is an adopter-visible change to `provael --help`. "
    "Order is not sorted, because Typer prints commands in registration order and a split that "
    "re-registers them in a different order moves what a reader sees."
)


# DUCK-TYPED, NOT ISINSTANCE. typer vendors click as `typer._click` and ships no top-level
# `click`, and the vendored `core` exports `Command` and `Context` but not `Group` — so an
# isinstance check against a click class is a bet on an internal layout that has already moved
# once. "Has list_commands" is what actually distinguishes a group, in every click version.
def _is_group(cmd: Any) -> bool:
    return callable(getattr(cmd, "list_commands", None))


def _param(param: Any) -> dict[str, Any]:
    return {
        "name": param.name,
        "opts": list(param.opts),
        "secondary_opts": list(param.secondary_opts),
        "required": bool(param.required),
        "is_flag": bool(getattr(param, "is_flag", False)),
        "help": getattr(param, "help", None),
    }


def _command(name: str, cmd: Any, ctx: Any) -> dict[str, Any]:
    entry: dict[str, Any] = {
        "name": name,
        "help": (cmd.help or "").strip(),
        "short_help": (cmd.short_help or "").strip() or None,
        "params": [_param(p) for p in cmd.params],
    }
    if _is_group(cmd):
        sub_ctx = type(ctx)(cmd, info_name=name, parent=ctx)
        entry["commands"] = [
            _command(sub, cmd.get_command(sub_ctx, sub), sub_ctx)
            for sub in cmd.list_commands(sub_ctx)
        ]
    return entry


def build() -> dict[str, Any]:
    # `Any`, because everything below is duck-typed: typer's vendored click exports `Command` and
    # `Context` but not `Group`, so mypy sees `get_command` return a `Command` that has neither
    # `list_commands` nor `get_command`. `_is_group` is the real check.
    root: Any = get_command(app)
    if not _is_group(root):  # pragma: no cover - would mean the CLI stopped having subcommands
        raise RuntimeError("provael's Typer app no longer renders as a command group")
    from typer._click.core import Context  # the one vendored name that is stable

    ctx = Context(root, info_name="provael")
    return {
        "$schema": "provael-cli-surface/1",
        "note": NOTE,
        "help": (root.help or "").strip(),
        "commands": [
            _command(name, root.get_command(ctx, name), ctx)
            for name in root.list_commands(ctx)
        ],
    }


def render() -> str:
    # sort_keys inside each object is fine — it is the LISTS whose order carries meaning.
    return json.dumps(build(), indent=1, sort_keys=True) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Snapshot the CLI surface.")
    parser.add_argument("--check", action="store_true", help="fail instead of writing")
    args = parser.parse_args(argv)

    rendered = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != rendered:
            print(
                f"{OUT.relative_to(ROOT)} disagrees with the CLI this tree builds. If you meant "
                "to change `provael --help`, run `make gen-cli-surface` and say so in the commit. "
                "If you were refactoring, you moved the surface.",
                file=sys.stderr,
            )
            return 1
        print(f"ok       {OUT.relative_to(ROOT)}")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
