"""Write `watch/registry.json` — the canonical registry counts, for downstream consumers.

WHY THIS EXISTS. www.provael.com restated the family and attack counts in prose across four
surfaces, and all four disagreed at once: "15 attack families", "28 adversarial attacks across 15
adversarial families", "Four families", and a llms.txt copy of the same. The site now derives them,
and it needs something machine-readable to derive them FROM.

WHY NOT THE EVIDENCE MANIFEST, which already carries a `registry` block. Because it counts the
`control` family as adversarial and this artifact does not — 17 against 16 for the same registry.
Two conventions, one number, and copying across them is exactly how a coverage claim inflates by a
family. This file publishes one convention and names it in its own `note`.

Regenerated by `.github/workflows/coverage-badge.yml`, which already commits to `watch/`.
"""

from __future__ import annotations

import json
from pathlib import Path

from provael.coverage import coverage_json

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "watch" / "registry.json"

NOTE = (
    "GENERATED by scripts/gen_registry_artifact.py. Do not hand-edit: the point of this file "
    "is that no human types these numbers. www.provael.com fetches it so the site's family and "
    "attack counts derive from this registry instead of being restated in prose — four site "
    "surfaces disagreed simultaneously before it existed. adversarialFamilies and "
    "adversarialAttacks EXCLUDE the `baseline` and `control` families; familiesTotal and "
    "attacksTotal include them. Those two conventions are not interchangeable, and mixing them "
    "is how a coverage claim inflates by one family. A THIRD convention sits beside those two: "
    "policies and suites count what is REGISTERED, while runnablePolicies and runnableSuites "
    "exclude the adapters and suites DECLARED as scaffolding — implemented and unit-tested, but "
    "never once run. scaffoldingPolicyNames and scaffoldingSuiteNames say which, so a consumer can "
    "render the reason rather than only the shortfall. Registered and runnable are not "
    "interchangeable either, and reading the registered total as the runnable one is how "
    "www.provael.com came to publish 5 suites beside a registry that said 6."
)


def main() -> None:
    counts = json.loads(coverage_json())
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        json.dumps({"$schema": "provael-registry-counts/1", "note": NOTE, **counts},
                   indent=1, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
