#!/usr/bin/env python3
"""Publish the current release as an artifact, so a consumer derives it instead of copying it.

WHY THIS EXISTS. `watch/` is the consumption surface: registry.json carries the counts,
freshness.json the badge, measurements.json the per-measurement ledger, coverage.json the coverage
total. There was no release artifact, so the one fact a consumer restates most often — which
version is current — was the one fact it could not derive.

www.provael.com kept a copied facts file refreshed on the release cadence, and the copy went stale
the moment a release shipped without someone remembering to re-pin it. On 6 September 2026, 14
built pages rendered v0.39.3 against a repo, tag, GitHub release and PyPI all at 0.39.4. The worst
of them was /security, which told a reporter to reproduce on "the latest release on PyPI (currently
v0.39.3)" — a page whose whole job is routing a vulnerability report at a reproducible version.

WHAT THIS FILE DELIBERATELY DOES NOT CARRY. No commit sha and no published_at timestamp. This
script runs offline, so it could only invent them or shell out to git and hope the checkout is the
one that shipped. An unverifiable field in a trust artifact is worse than a missing one: a consumer
cannot tell a guess from a fact, and the whole point of `watch/` is that no human types these
values. If those fields are ever wanted, they belong in the release workflow where the CI context
actually knows them, and the note must then say they came from CI.

DETERMINISM. Output is a pure function of `provael.__version__`, so re-running on an unchanged tree
is a no-op and `--check` is meaningful. That is what wires it into `make check-docs`: the artifact
cannot silently disagree with the package it describes.

Usage::

    python scripts/gen_release_artifact.py            # rewrite
    python scripts/gen_release_artifact.py --check    # fail if a rewrite would change anything
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from provael import __version__  # noqa: E402  - after the sys.path insert above

OUT = ROOT / "watch" / "release.json"

NOTE = (
    "GENERATED by scripts/gen_release_artifact.py from provael.__version__, which hatch also reads "
    "as the package version. Do not hand-edit: the point of this file is that no human types the "
    "release number. It exists because a consumer that keeps its own copy goes stale the moment a "
    "release ships without someone remembering to re-pin it, which is how www.provael.com came to "
    "serve v0.39.3 on 14 pages while the tag, the GitHub release and PyPI all said 0.39.4. "
    "`tag` is the git tag the release workflow publishes from and `pypi` is the same string, "
    "because the workflow publishes from that tag. There is deliberately NO commit sha and NO "
    "published_at: this script runs offline and could only guess at them, and an unverifiable "
    "field in a trust artifact is worse than a missing one."
)


def build() -> dict[str, object]:
    """The artifact, as a plain dict. Every value derives from one source."""
    return {
        "$schema": "provael-release/1",
        "note": NOTE,
        "version": __version__,
        "tag": f"v{__version__}",
        "pypi": __version__,
    }


def render() -> str:
    return json.dumps(build(), indent=1, sort_keys=True) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Publish watch/release.json.")
    parser.add_argument("--check", action="store_true", help="fail instead of writing")
    args = parser.parse_args(argv)

    rendered = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != rendered:
            print(
                f"{OUT.relative_to(ROOT)} disagrees with provael.__version__ ({__version__}). "
                "Run `make gen-release` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"ok       {OUT.relative_to(ROOT)} ({__version__})")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({__version__})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
